base_app/ads/urls.py
from django.contrib import admin
from django.urls import path
from ads import views

urlpatterns = [
    path('', views.IndexHome.as_view(), name='home_page'),
    path('create_ad/', views.CreateAd.as_view(), name='create_ad'),
    path('show_ads/', views.ShowAds.as_view(), name='show_ads'),
    path('show_ads/<int:pk>/', views.ShowAd.as_view(), name='show_ad'),

    path('edit_ad/<int:pk>', views.EditAd.as_view(), name='edit_ad'),
    path('delete_ad/<int:pk>', views.DeleteAd.as_view(), name='delete_ad'),

    path('exchange/<int:pk>/', views.CreateExchange.as_view(), name='exchange'),
    path('exchange/<int:ad_sender_id>/to/<int:ad_receiver_id>/', 
         views.CreateExchange.as_view(), 
         name='create_exchange'),
    path('proposal/<int:pk>/', views.ProposalDetailView.as_view(), name='proposal_detail'),

    path('proposal/<int:pk>/accept/', views.accept_proposal, name='accept_proposal'),
    path('proposal/<int:pk>/reject/', views.reject_proposal, name='reject_proposal'),

]

base_app/base_app/urls.py
from django.contrib import admin
from django.urls import path, include
from ads import views
from . import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ads.urls')),
    path('users/', include(('users.urls', 'users'), namespace='users'))
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = views.page_not_found

base_app/users/urls.py
from django.contrib import admin
from django.urls import path

from users import views

urlpatterns = [
    path('login/', views.UserLogin.as_view(), name='login'),
    path('logout/', views.LogoutUser.as_view(), name='logout'),

    path('password-change/',views.UserPassChange.as_view(), name='password_change'),
    path('password-change/done/',views.PasswordChangeDoneViewMofify.as_view(), name='password_change_done'),
    path('password_reset/', views.PassReset.as_view(), name='password_reset'),
    path('password_reset/done/', views.PassResetDone.as_view(), name='password_reset_done'),

    path('password_reset/<uidb64>/<token>/', views.PassConfirm.as_view(), name='password_reset_confirm'),
    path('password_reset/complete/', views.PassResetComplete.as_view(), name='password_reset_complete'),

    path('register/', views.RegisterUser.as_view(), name='register'),
    path('register_done/', views.RegisterUserDone.as_view(), name='register_done'),
    
    path('profile/', views.ProfileUser.as_view(), name='profile'),
]

base_app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>{{ title }}</title>
	<link type="text/css" href="{% static 'ads/css/styles.css' %}" rel="stylesheet"/>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
{% include 'ads/includes/nav.html' %}

{% if user.is_authenticated %}
    <form style="display:inline-block" method="post" action="{% url 'users:logout' %}">
    {% csrf_token %}
    <button type="submit">Выйти</button></form>
    <li><a href="{% url 'users:profile' %}">{{ user.username }}</a></li>
    {% if user.first_name %}
        <li class="last">{{ user.first_name }}</li>
    {% else %}
        <li class="last">No Public Name</li>
    {% endif %}
{% else %}
    <li class="last"><a href="{% url 'users:login' %}">Вход</a> | <a href="{% url 'users:register' %}">Регистрация</a></li>
    <li class="last">Anon</li>
    {% endif %}
	
{% block content %} {% endblock %}
</body>
</html>