base_app/ads/urls.py
from django.contrib import admin
from django.urls import path
from ads import views

urlpatterns = [
    path('', views.IndexHome.as_view(), name='home_page'),
    path('create_ad/', views.CreateAd.as_view(), name='create_ad'),
    path('show_ads/', views.ShowAds.as_view(), name='show_ads'),
    path('show_ads/<int:pk>/', views.ShowAd.as_view(), name='show_ad'),

    path('edit_ad/<int:pk>', views.EditAd.as_view(), name='edit_ad'),
    path('delete_ad/<int:pk>', views.DeleteAd.as_view(), name='delete_ad'),

    path('exchange/<int:pk>/', views.CreateExchange.as_view(), name='exchange'),
    path('exchange/<int:ad_sender_id>/to/<int:ad_receiver_id>/', 
         views.CreateExchange.as_view(), 
         name='create_exchange'),
    path('proposal/<int:pk>/', views.ProposalDetailView.as_view(), name='proposal_detail'),

    path('proposal/<int:pk>/accept/', views.accept_proposal, name='accept_proposal'),
    path('proposal/<int:pk>/reject/', views.reject_proposal, name='reject_proposal'),

]

base_app/base_app/urls.py
from django.contrib import admin
from django.urls import path, include
from ads import views
from . import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ads.urls')),
    path('users/', include(('users.urls', 'users'), namespace='users'))
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = views.page_not_found

base_app/users/urls.py
from django.contrib import admin
from django.urls import path

from users import views

urlpatterns = [
    path('login/', views.UserLogin.as_view(), name='login'),
    path('logout/', views.LogoutUser.as_view(), name='logout'),

    path('password-change/',views.UserPassChange.as_view(), name='password_change'),
    path('password-change/done/',views.PasswordChangeDoneViewMofify.as_view(), name='password_change_done'),
    path('password_reset/', views.PassReset.as_view(), name='password_reset'),
    path('password_reset/done/', views.PassResetDone.as_view(), name='password_reset_done'),

    path('password_reset/<uidb64>/<token>/', views.PassConfirm.as_view(), name='password_reset_confirm'),
    path('password_reset/complete/', views.PassResetComplete.as_view(), name='password_reset_complete'),

    path('register/', views.RegisterUser.as_view(), name='register'),
    path('register_done/', views.RegisterUserDone.as_view(), name='register_done'),
    
    path('profile/', views.ProfileUser.as_view(), name='profile'),
]

base_app/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

from base_app.settings import DEFAULT_USER_IMAGE

# Create your models here.
class User(AbstractUser):
    photo = models.ImageField(
        upload_to='users/%Y/%m/%d', 
        blank=True, 
        null=True, 
        verbose_name='Photo')
    date_birth = models.DateField(blank=True, null=True, verbose_name='Birthday')

base_app/users/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import PasswordChangeForm
from datetime import datetime, date, timedelta
from ads.models import ExchangeProposal
from django.db import models

class LoginUserForm(AuthenticationForm):
    username = forms.CharField(label='Логин', widget=forms.TextInput(attrs={'class':'form-input'}))
    password = forms.CharField(label='Пароль', widget=forms.PasswordInput(attrs={'class':'form-input'}))
    class Meta:
        model = get_user_model()
        fields = ['username''password']


class RegisterUserForm(UserCreationForm):
    username = forms.CharField(label='Логин', widget=forms.TextInput(attrs={'class':'form-input'}))
    first_name = forms.CharField(label='Публичное Имя', widget=forms.TextInput(attrs={'class':'form-input'}), initial='Anon')
    password1 = forms.CharField(label='Пароль', widget=forms.PasswordInput(attrs={'class':'form-input'}))
    password2 = forms.CharField(label='Повторите Пароль', widget=forms.PasswordInput(attrs={'class':'form-input'}))
    email = forms.EmailField(label='Почта', required=False)
    year_now = datetime.now().year
    date_birth = forms.DateField(
        label='Дата Рождения', 
        widget=forms.SelectDateWidget(
            years=range(year_now-120, year_now+1),
            attrs={'class': 'form-select'}
        ), 
        required=False,
        initial=date(year_now-21,1,1)
    )
    class Meta:
        model = get_user_model()
        fields = ['username', 'first_name', 'password1', 'password2', 'email']

        widgets = {
            'emai':forms.TextInput(attrs={'class':'form-input'}),
            'first_name':forms.TextInput(attrs={'class':'form-input'})
            }
        
class ProfileUserForm(forms.ModelForm):
    username = forms.CharField(disabled=True, label='Логин', widget=forms.TextInput(attrs={'class':'form-input'}), required=False)
    email = forms.EmailField(label='Почта', required=False)
    first_name = forms.CharField(label='Публичное Имя', widget=forms.TextInput(attrs={'class':'form-input'}), required=False)
    year_now = datetime.now().year
    date_birth = forms.DateField(
        label='Дата Рождения', 
        widget=forms.SelectDateWidget(
            years=tuple(range(year_now-120, year_now-0)),
            attrs={'class': 'form-select'}
                                      )
        )
    
    
    message = forms.ModelChoiceField(
        queryset=ExchangeProposal.objects.none(),
        label='Сообщения',
        required=False,
        widget=forms.Select(attrs={'class': 'form-select'})
    )

    
    class Meta:
        model = get_user_model()
        fields = ['first_name', 'email', 'photo', 'date_birth']

        widgets = {
            'first_name':forms.TextInput(attrs={'class':'form-input'}),
            'email':forms.TextInput(attrs={'class':'form-input'}),
            }
        
    def __init__(self, *args, **kwargs):
        user = kwargs.get('instance')
        super().__init__(*args, **kwargs)
        
        if user and user.pk:
            self.fields['message'].queryset = ExchangeProposal.objects.filter(
                models.Q(ad_receiver__user=user)
            ).order_by('-created_at')
            
        

class UserPasswordForm(PasswordChangeForm):
    old_password = forms.CharField(label='Old password', widget=forms.PasswordInput(attrs={'class':'form-input'}))
    new_password1 = forms.CharField(label='New Password', widget=forms.PasswordInput(attrs={'class':'form-input'}))
    new_password2 = forms.CharField(label='Confirm password', widget=forms.PasswordInput(attrs={'class':'form-input'}))

base_app/users/views.py
from django.urls import reverse, reverse_lazy
from django.shortcuts import render, redirect
from django.contrib.auth.views import LoginView, LogoutView, PasswordChangeView, PasswordChangeDoneView, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.views.generic import TemplateView, ListView, DetailView, FormView, CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import get_user_model
import logging

import base_app.settings as sett 
from .forms import LoginUserForm, RegisterUserForm, ProfileUserForm, UserPasswordForm
from ads.utils import DataMixin

logger = logging.getLogger(__name__)

class UserLogin(DataMixin, LoginView):
    form_class = LoginUserForm
    template_name = 'users/login.html'
    title_page = 'Вход'
    

class RegisterUser(DataMixin, CreateView):
    form_class = RegisterUserForm
    template_name = 'users/register.html'
    success_url = reverse_lazy('users:register_done')
    title_page = 'Регистрация'


class RegisterUserDone(DataMixin, TemplateView):
    template_name = 'users/register_200.html'

class LogoutUser(LogoutView):pass

class ProfileUser(DataMixin, LoginRequiredMixin, UpdateView):
    model = get_user_model()
    form_class = ProfileUserForm
    template_name = 'users/profile.html'
    title_page = 'Профиль'
    extra_context = {'default_image': sett.DEFAULT_USER_IMAGE}
    
    def get_success_url(self):
        return reverse_lazy('users:profile')
    
    def get_object(self):
        return self.request.user
    
    def form_valid(self, form):

        selected_message = form.cleaned_data.get('message')
        logger.debug(f'{selected_message}')
        if selected_message:
            return redirect('proposal_detail', pk=selected_message.pk)
        return super().form_valid(form)
    
    
class UserPassChange(DataMixin, LoginRequiredMixin, PasswordChangeView):
    form_class = UserPasswordForm
    success_url = reverse_lazy("users:password_change_done")
    template_name = "users/password_change_form.html"


class PasswordChangeDoneViewMofify(DataMixin, PasswordChangeDoneView):
    template_name = 'users/password_change_done.html'


class PassReset(DataMixin, PasswordResetView):
    template_name = 'users/password_reset_form.html'
    email_template_name = 'users/password_reset_email.html'
    success_url = reverse_lazy('users:password_reset_done')

class PassResetDone(DataMixin, PasswordResetDoneView):
    template_name = 'users/password_reset_done.html'

class PassConfirm(DataMixin, PasswordResetConfirmView):
    template_name = 'users/password_reset_confirm.html'
    success_url = reverse_lazy('users:password_reset_complete')

class PassResetComplete(DataMixin, PasswordResetCompleteView):
    template_name = 'users/password_reset_complete.html'

base_app/users/templates/users/login.html
{% extends 'base.html' %}
{% block content %}
<h1>{{ title }}</h1>
<form method="POST">
    {% csrf_token %}
    <div class="form-error">{{ form.non_fields_errors }}</div>
    {% for f in form %}
    <p><label class="form-label" for="{{ f.id_for_label }}">{{ f.label  }}</label>{{ f }}</p>
    <div class="form-error">{{ f.errors }}</div>
    {% endfor %}
    <p><button type="submit">Подтвердить</button>
    <p><a href="{% url 'users:password_reset' %}">Забыли пароль?</a></p>
</form>
{% endblock %}

base_app/users/templates/users/logout.html
{% extends 'base.html' %}
{% block content %}
{% if user.is_authenticated %}
    <form style="display:inline-block" method="POST" action="{% url 'users/logout.html' %}">
    {% csrf_token %}
    <button type="submit">{{ title }}</button></form>
    <li class="last">{{ user.username }}</li>
{% endif %}
{% endblock %}

base_app/users/templates/users/password_change_done.html
{% extends 'base.html' %}
{% block content %}
<p>Password was changed successfully!</p>
<p><a href="{% url 'users:profile' %}">Back to the profile</a></p>
{% endblock %}

base_app/users/templates/users/password_change_form.html
{% extends 'base.html' %}
{% block content %}
<h1>Password change</h1>
<form method="POST">
    {% csrf_token %}
    <div class="form-error">{{ form.non_fields_errors }}</div>
    {% for f in form %}
    <p><label class="form-label" for="{{ f.id_for_label }}">{{ f.label  }}</label>{{ f }}</p>
    <div class="form-error">{{ f.errors }}</div>
    {% endfor %}
    <p><button type="submit">Send</button>
</form>
<hr>
{% endblock %}

base_app/users/templates/users/password_reset_complete.html
{% extends 'base.html' %}
{% block content %}
<p>Password was changed successfully!</p>
{% endblock %}

base_app/users/templates/users/password_reset_confirm.html
{% extends 'base.html' %}
{% block content %}
<h1>Password change</h1>
<form method="POST">
    {% csrf_token %}
    <div class="form-error">{{ form.non_fields_errors }}</div>
    {% for f in form %}
    <p><label class="form-label" for="{{ f.id_for_label }}">{{ f.label  }}</label>{{ f }}</p>
    <div class="form-error">{{ f.errors }}</div>
    {% endfor %}
    <p><button type="submit">Send</button>
</form>
<hr>
{% endblock %}

base_app/users/templates/users/password_reset_done.html
{% extends 'base.html' %}
{% block content %}
<h1>Password reset</h1>
<p>We have sended to your email instructions to reset the password.</p>
<p>Please check your emal.</p>
{% endblock %}

base_app/users/templates/users/password_reset_email.html
{% load i18n %}{% autoescape off %}
{% blocktranslate %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktranslate %}

{% translate "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% translate 'Your username, in case you’ve forgotten:' %} {{ user.get_username }}

{% translate "Thanks for using our site!" %}

{% blocktranslate %}The {{ site_name }} team{% endblocktranslate %}

{% endautoescape %}

base_app/users/templates/users/password_reset_form.html
{% extends 'base.html' %}
{% block content %}
<h1>Password reset</h1>
<form method="POST">
    {% csrf_token %}
    <div class="form-error">{{ form.non_fields_errors }}</div>
    {% for f in form %}
    <p><label class="form-label" for="{{ f.id_for_label }}">{{ f.label  }}</label>{{ f }}</p>
    <div class="form-error">{{ f.errors }}</div>
    {% endfor %}
    <p><button type="submit">Send</button>
</form>
<hr>
{% endblock %}

base_app/users/templates/users/profile.html
{% extends 'base.html' %}
{% block content %}
<h1>{{ title }}</h1>

{% if user.photo %}
<br><img src="{{ user.photo.url }}"  width="200" height="200">
{% else %}
<br><img src="{{ default_image }}"  width="200" height="200">
{% endif %}
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="form-error">{{ form.non_fields_errors }}</div>
    {% for f in form %}
    <p><label class="form-label" for="{{ f.id_for_label }}">{{ f.label  }}</label>{{ f }}</p>
    <div class="form-error">{{ f.errors }}</div>
    {% endfor %}
    <p><button type="submit">Подтвердить</button>
</form>
<hr>
<a href="{% url 'users:password_change' %}">Сменить пароль</a>
{% endblock %}

base_app/users/templates/users/register.html
{% extends 'base.html' %}
{% block content %}
<h1>{{ title }}</h1>
<form method="POST">
    {% csrf_token %}
    <input type="hidden" name="next" value="{{ next }}"/>
    <div class="form-error">{{ form.non_fields_errors }}</div>
    {% for f in form %}
    <p><label class="form-label" for="{{ f.id_for_label }}">{{ f.label  }}</label>{{ f }}</p>
    <div class="form-error">{{ f.errors }}</div>
    {% endfor %}
    <p><button type="submit">Подтвердить</button>
</form>
{% endblock %}

base_app/users/templates/users/register_200.html
{% extends 'base.html' %}
{% block content %}
<p>Registration was success!</p>
{% endblock %}